version: '2.2'
services:
  rabbitmq:
    image: library/rabbitmq:3.8-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"